language: python

python:
    - 2.6
    - 2.7
    - pypy

env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
  - TWISTED=Twisted==12.3.0
  - TWISTED=Twisted==12.2.0
  - TWISTED=Twisted==12.1.0

install:
  - pip install $TWISTED --use-mirrors
  - pip install -r requirements-dev.txt --use-mirrors
  - python setup.py install

script:
  - pep8 treq
  - pyflakes treq
  - trial treq
